language: cpp
cache:
  directories:
    - /tmp/Rack
osx_image: xcode9.2
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install librtlsdr-dev git libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libgl1-mesa-dev libglu1-mesa-dev zlib1g-dev libasound2-dev libgtk2.0-dev unzip cmake libudev-dev libusb-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install librtlsdr libusb; fi
before_script:
  - git clone https://github.com/VCVRack/Rack.git /tmp/Rack || cd /tmp/Rack && git pull
  - cd /tmp/Rack
  - git submodule update --init --recursive
  - make dep #> /dev/null
  - make
  - rm -rf /tmp/Rack/plugins/sdr || true
  - cp -r $TRAVIS_BUILD_DIR /tmp/Rack/plugins/sdr
  - if [ $TRAVIS_OS_NAME == linux ]; then CC=gcc-7 && CXX=g++-7; fi
script: cd /tmp/Rack/plugins/sdr && VERSION=0.0.0 make dist
